-- AlterTable
ALTER TABLE "Plan" ADD COLUMN     "allowAgencyBranding" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowBasicPdf" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowBasicScan" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowClientManagement" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowHidePoweredBy" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowManualReview" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowPriorityGuidance" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowPrioritySupport" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowProfessionalPdf" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowProfessionalScan" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowShareLinks" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "allowWhiteLabel" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "basicPdfCredits" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "basicScanLimitPerDay" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "deepManualReviewCredits" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lightManualReviewCredits" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "preferredPaymentProvider" TEXT,
ADD COLUMN     "professionalPdfCredits" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "professionalScanLimitPerDay" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "stripeEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "totalReportCredits" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "billingType" SET DEFAULT 'ONE_TIME';

-- Backfill entitlement matrix for existing canonical plans by slug.
UPDATE "Plan"
SET
  "price" = 0,
  "currency" = 'USD',
  "billingType" = 'FREE',
  "allowBasicScan" = true,
  "allowProfessionalScan" = false,
  "basicScanLimitPerDay" = 3,
  "professionalScanLimitPerDay" = 0,
  "allowBasicPdf" = false,
  "allowProfessionalPdf" = false,
  "basicPdfCredits" = 0,
  "professionalPdfCredits" = 0,
  "totalReportCredits" = 0,
  "allowManualReview" = false,
  "lightManualReviewCredits" = 0,
  "deepManualReviewCredits" = 0,
  "allowPriorityGuidance" = false,
  "allowWhiteLabel" = false,
  "allowClientManagement" = false,
  "allowShareLinks" = false,
  "allowHidePoweredBy" = false,
  "allowAgencyBranding" = false,
  "allowPrioritySupport" = false,
  "stripeEnabled" = false,
  "reportCredits" = 0,
  "whiteLabelEnabled" = false,
  "clientManagementEnabled" = false,
  "shareLinkEnabled" = false,
  "manualReviewEnabled" = false
WHERE "slug" = 'free-demo';

UPDATE "Plan"
SET
  "price" = 19,
  "currency" = 'USD',
  "billingType" = 'ONE_TIME',
  "allowBasicScan" = true,
  "allowProfessionalScan" = false,
  "basicScanLimitPerDay" = 25,
  "professionalScanLimitPerDay" = 0,
  "allowBasicPdf" = true,
  "allowProfessionalPdf" = false,
  "basicPdfCredits" = 1,
  "professionalPdfCredits" = 0,
  "totalReportCredits" = 1,
  "allowManualReview" = false,
  "lightManualReviewCredits" = 0,
  "deepManualReviewCredits" = 0,
  "allowPriorityGuidance" = false,
  "allowWhiteLabel" = false,
  "allowClientManagement" = false,
  "allowShareLinks" = false,
  "allowHidePoweredBy" = false,
  "allowAgencyBranding" = false,
  "allowPrioritySupport" = false,
  "stripeEnabled" = false,
  "reportCredits" = 1,
  "whiteLabelEnabled" = false,
  "clientManagementEnabled" = false,
  "shareLinkEnabled" = false,
  "manualReviewEnabled" = false
WHERE "slug" = 'basic-report';

UPDATE "Plan"
SET
  "price" = 49,
  "currency" = 'USD',
  "billingType" = 'ONE_TIME',
  "allowBasicScan" = true,
  "allowProfessionalScan" = true,
  "basicScanLimitPerDay" = 25,
  "professionalScanLimitPerDay" = 1,
  "allowBasicPdf" = true,
  "allowProfessionalPdf" = true,
  "basicPdfCredits" = 0,
  "professionalPdfCredits" = 1,
  "totalReportCredits" = 1,
  "allowManualReview" = true,
  "lightManualReviewCredits" = 1,
  "deepManualReviewCredits" = 0,
  "allowPriorityGuidance" = false,
  "allowWhiteLabel" = false,
  "allowClientManagement" = false,
  "allowShareLinks" = false,
  "allowHidePoweredBy" = false,
  "allowAgencyBranding" = false,
  "allowPrioritySupport" = false,
  "stripeEnabled" = false,
  "reportCredits" = 1,
  "whiteLabelEnabled" = false,
  "clientManagementEnabled" = false,
  "shareLinkEnabled" = false,
  "manualReviewEnabled" = true
WHERE "slug" = 'pro-report';

UPDATE "Plan"
SET
  "price" = 49,
  "currency" = 'USD',
  "billingType" = 'MONTHLY',
  "allowBasicScan" = true,
  "allowProfessionalScan" = true,
  "basicScanLimitPerDay" = 50,
  "professionalScanLimitPerDay" = 25,
  "allowBasicPdf" = true,
  "allowProfessionalPdf" = true,
  "basicPdfCredits" = 0,
  "professionalPdfCredits" = 25,
  "totalReportCredits" = 25,
  "allowManualReview" = false,
  "lightManualReviewCredits" = 0,
  "deepManualReviewCredits" = 0,
  "allowPriorityGuidance" = false,
  "allowWhiteLabel" = true,
  "allowClientManagement" = true,
  "allowShareLinks" = true,
  "allowHidePoweredBy" = false,
  "allowAgencyBranding" = true,
  "allowPrioritySupport" = false,
  "stripeEnabled" = false,
  "reportCredits" = 25,
  "whiteLabelEnabled" = true,
  "clientManagementEnabled" = true,
  "shareLinkEnabled" = true,
  "manualReviewEnabled" = false
WHERE "slug" = 'agency-starter';

UPDATE "Plan"
SET
  "price" = 99,
  "currency" = 'USD',
  "billingType" = 'MONTHLY',
  "allowBasicScan" = true,
  "allowProfessionalScan" = true,
  "basicScanLimitPerDay" = 100,
  "professionalScanLimitPerDay" = 100,
  "allowBasicPdf" = true,
  "allowProfessionalPdf" = true,
  "basicPdfCredits" = 0,
  "professionalPdfCredits" = 100,
  "totalReportCredits" = 100,
  "allowManualReview" = true,
  "lightManualReviewCredits" = 0,
  "deepManualReviewCredits" = 0,
  "allowPriorityGuidance" = true,
  "allowWhiteLabel" = true,
  "allowClientManagement" = true,
  "allowShareLinks" = true,
  "allowHidePoweredBy" = true,
  "allowAgencyBranding" = true,
  "allowPrioritySupport" = true,
  "stripeEnabled" = false,
  "reportCredits" = 100,
  "whiteLabelEnabled" = true,
  "clientManagementEnabled" = true,
  "shareLinkEnabled" = true,
  "manualReviewEnabled" = true
WHERE "slug" = 'agency-pro';

UPDATE "Plan"
SET
  "price" = 149,
  "currency" = 'USD',
  "billingType" = 'ADDON',
  "allowBasicScan" = false,
  "allowProfessionalScan" = false,
  "basicScanLimitPerDay" = 0,
  "professionalScanLimitPerDay" = 0,
  "allowBasicPdf" = false,
  "allowProfessionalPdf" = false,
  "basicPdfCredits" = 0,
  "professionalPdfCredits" = 0,
  "totalReportCredits" = 0,
  "allowManualReview" = true,
  "lightManualReviewCredits" = 0,
  "deepManualReviewCredits" = 1,
  "allowPriorityGuidance" = false,
  "allowWhiteLabel" = false,
  "allowClientManagement" = false,
  "allowShareLinks" = false,
  "allowHidePoweredBy" = false,
  "allowAgencyBranding" = false,
  "allowPrioritySupport" = false,
  "stripeEnabled" = false,
  "reportCredits" = 0,
  "whiteLabelEnabled" = false,
  "clientManagementEnabled" = false,
  "shareLinkEnabled" = false,
  "manualReviewEnabled" = true
WHERE "slug" = 'manual-review-addon';
