import { BillingType, PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const plans = [
  {
    name: "Free Demo",
    slug: "free-demo",
    price: "0",
    currency: "USD",
    billingType: BillingType.FREE,
    allowBasicScan: true,
    allowProfessionalScan: false,
    basicScanLimitPerDay: 3,
    professionalScanLimitPerDay: 0,
    allowBasicPdf: false,
    allowProfessionalPdf: false,
    basicPdfCredits: 0,
    professionalPdfCredits: 0,
    totalReportCredits: 0,
    allowManualReview: false,
    lightManualReviewCredits: 0,
    deepManualReviewCredits: 0,
    allowPriorityGuidance: false,
    allowWhiteLabel: false,
    allowClientManagement: false,
    allowShareLinks: false,
    allowHidePoweredBy: false,
    allowAgencyBranding: false,
    allowPrioritySupport: false,
    preferredPaymentProvider: null,
    stripeEnabled: false,
    lemonEnabled: false,
    reportCredits: 0,
    clientManagementEnabled: false,
    shareLinkEnabled: false,
    whiteLabelEnabled: false,
    manualReviewEnabled: false,
    isActive: true,
  },
  {
    name: "Basic Report",
    slug: "basic-report",
    price: "19",
    currency: "USD",
    billingType: BillingType.ONE_TIME,
    allowBasicScan: true,
    allowProfessionalScan: false,
    basicScanLimitPerDay: 25,
    professionalScanLimitPerDay: 0,
    allowBasicPdf: true,
    allowProfessionalPdf: false,
    basicPdfCredits: 1,
    professionalPdfCredits: 0,
    totalReportCredits: 1,
    allowManualReview: false,
    lightManualReviewCredits: 0,
    deepManualReviewCredits: 0,
    allowPriorityGuidance: false,
    allowWhiteLabel: false,
    allowClientManagement: false,
    allowShareLinks: false,
    allowHidePoweredBy: false,
    allowAgencyBranding: false,
    allowPrioritySupport: false,
    preferredPaymentProvider: null,
    stripeEnabled: false,
    lemonEnabled: false,
    reportCredits: 1,
    stripeMode: "payment",
    clientManagementEnabled: false,
    shareLinkEnabled: false,
    whiteLabelEnabled: false,
    manualReviewEnabled: false,
    isActive: true,
  },
  {
    name: "Pro Report",
    slug: "pro-report",
    price: "49",
    currency: "USD",
    billingType: BillingType.ONE_TIME,
    allowBasicScan: true,
    allowProfessionalScan: true,
    basicScanLimitPerDay: 25,
    professionalScanLimitPerDay: 1,
    allowBasicPdf: true,
    allowProfessionalPdf: true,
    basicPdfCredits: 0,
    professionalPdfCredits: 1,
    totalReportCredits: 1,
    allowManualReview: true,
    lightManualReviewCredits: 1,
    deepManualReviewCredits: 0,
    allowPriorityGuidance: false,
    allowWhiteLabel: false,
    allowClientManagement: false,
    allowShareLinks: false,
    allowHidePoweredBy: false,
    allowAgencyBranding: false,
    allowPrioritySupport: false,
    preferredPaymentProvider: null,
    stripeEnabled: false,
    lemonEnabled: false,
    reportCredits: 1,
    stripeMode: "payment",
    clientManagementEnabled: false,
    shareLinkEnabled: false,
    whiteLabelEnabled: false,
    manualReviewEnabled: true,
    isActive: true,
  },
  {
    name: "Agency Starter",
    slug: "agency-starter",
    price: "49",
    currency: "USD",
    billingType: BillingType.MONTHLY,
    allowBasicScan: true,
    allowProfessionalScan: true,
    basicScanLimitPerDay: 50,
    professionalScanLimitPerDay: 25,
    allowBasicPdf: true,
    allowProfessionalPdf: true,
    basicPdfCredits: 0,
    professionalPdfCredits: 25,
    totalReportCredits: 25,
    allowManualReview: false,
    lightManualReviewCredits: 0,
    deepManualReviewCredits: 0,
    allowPriorityGuidance: false,
    allowWhiteLabel: true,
    allowClientManagement: true,
    allowShareLinks: true,
    allowHidePoweredBy: false,
    allowAgencyBranding: true,
    allowPrioritySupport: false,
    preferredPaymentProvider: null,
    stripeEnabled: false,
    lemonEnabled: false,
    reportCredits: 25,
    stripeMode: "subscription",
    clientManagementEnabled: true,
    shareLinkEnabled: true,
    whiteLabelEnabled: true,
    manualReviewEnabled: false,
    isActive: true,
  },
  {
    name: "Agency Pro",
    slug: "agency-pro",
    price: "99",
    currency: "USD",
    billingType: BillingType.MONTHLY,
    allowBasicScan: true,
    allowProfessionalScan: true,
    basicScanLimitPerDay: 100,
    professionalScanLimitPerDay: 100,
    allowBasicPdf: true,
    allowProfessionalPdf: true,
    basicPdfCredits: 0,
    professionalPdfCredits: 100,
    totalReportCredits: 100,
    allowManualReview: true,
    lightManualReviewCredits: 0,
    deepManualReviewCredits: 0,
    allowPriorityGuidance: true,
    allowWhiteLabel: true,
    allowClientManagement: true,
    allowShareLinks: true,
    allowHidePoweredBy: true,
    allowAgencyBranding: true,
    allowPrioritySupport: true,
    preferredPaymentProvider: null,
    stripeEnabled: false,
    lemonEnabled: false,
    reportCredits: 100,
    stripeMode: "subscription",
    clientManagementEnabled: true,
    shareLinkEnabled: true,
    whiteLabelEnabled: true,
    manualReviewEnabled: true,
    isActive: true,
  },
  {
    name: "Manual Review Add-on",
    slug: "manual-review-addon",
    price: "149",
    currency: "USD",
    billingType: BillingType.ADDON,
    allowBasicScan: false,
    allowProfessionalScan: false,
    basicScanLimitPerDay: 0,
    professionalScanLimitPerDay: 0,
    allowBasicPdf: false,
    allowProfessionalPdf: false,
    basicPdfCredits: 0,
    professionalPdfCredits: 0,
    totalReportCredits: 0,
    allowManualReview: true,
    lightManualReviewCredits: 0,
    deepManualReviewCredits: 1,
    allowPriorityGuidance: false,
    allowWhiteLabel: false,
    allowClientManagement: false,
    allowShareLinks: false,
    allowHidePoweredBy: false,
    allowAgencyBranding: false,
    allowPrioritySupport: false,
    preferredPaymentProvider: null,
    stripeEnabled: false,
    lemonEnabled: false,
    reportCredits: 0,
    clientManagementEnabled: false,
    shareLinkEnabled: false,
    whiteLabelEnabled: false,
    manualReviewEnabled: true,
    isActive: true,
  },
];

const creditPackages = [
  {
    id: "credit-package-credits-5",
    name: "5 PDF Credits",
    slug: "credits-5",
    price: "45",
    currency: "USD",
    reportCredits: 5,
    isActive: true,
  },
  {
    id: "credit-package-credits-10",
    name: "10 PDF Credits",
    slug: "credits-10",
    price: "85",
    currency: "USD",
    reportCredits: 10,
    isActive: true,
  },
  {
    id: "credit-package-credits-25",
    name: "25 PDF Credits",
    slug: "credits-25",
    price: "199",
    currency: "USD",
    reportCredits: 25,
    isActive: true,
  },
];

async function main() {
  for (const plan of plans) {
    await prisma.plan.upsert({
      where: { slug: plan.slug },
      update: plan,
      create: plan,
    });
  }

  for (const creditPackage of creditPackages) {
    await prisma.creditPackage.upsert({
      where: { slug: creditPackage.slug },
      update: {
        name: creditPackage.name,
        price: creditPackage.price,
        currency: creditPackage.currency,
        reportCredits: creditPackage.reportCredits,
        isActive: creditPackage.isActive,
      },
      create: creditPackage,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
